language: node_js
before_script:
     - "npm install -g se-interpreter"
script:
     - "se-interpreter test1/interpreter_config.json"

env:
    global:
    - SAUCE_USERNAME=w2gi
    - secure: "iwr0G7LifMf9REj3RCxSqmIcoIfZln0Sg2gEIkjBDgQ0Iv3kK82G4BsiYE5HSlygwrXjxsXBDNAjaRBuuOmihFyqn9sBh76rO0rQKmygqo7E5JVaD+zcvozg2IofsjJ3ehiJAT3QK6QvyOD5S1HkuiJi//MCMI5G/m2LChpqFl8="

